language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - pip install -U pip setuptools wheel
install:
  - travis_wait travis_retry pip install -r requirements.txt
script: "nosetests cem/tests --with-coverage --cover-package=cem"
